###
POST http://localhost:3000/api/users/auth/register
Content-Type: application/json

{
  "username": "radhouen",
  "email": "radhouen2@example.com",
  "password": "securepassword"
}


### 
# @name login
POST http://localhost:3000/api/users/auth/login
Content-Type: application/json

{
  "email": "bilel@example.com",
  "password": "newsecurepassword"
}
###
@token = {{login.response.body.$.token}}


###
# @name current-user
GET http://localhost:3000/api/users/current-user
Authorization: Bearer {{token}}

###
# @name admin-route
GET http://localhost:3000/api/users
Authorization: Bearer {{token}}

###
# @name update-user
PUT http://localhost:3000/api/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "bilel askri",
  "password": "newsecurepassword"
}

###
# @name delete-user
DELETE http://localhost:3000/api/users/1
Authorization: Bearer {{token}}