###
POST http://localhost:3000/api/users/auth/register
Content-Type: application/json

{
  "username": "Bilel",
  "email": "bilel@example.com",
  "password": "securepassword"
}


### 
# @name login
POST http://localhost:3000/api/users/auth/login
Content-Type: application/json

{
  "email": "johndoe2@example.com",
  "password": "securepassword"
}
###
@token = {{login.response.body.$.token}}


###
# @name current-user
GET http://localhost:3000/api/users/current-user
Authorization: Bearer {{token}}